config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts

  match '/', to: 'static_pages#home', as: 'root'
 

  match '/help',      to: 'static_pages#help',    as: 'help'
  match '/about',     to: 'static_pages#about',   as: 'about'
  match '/contact',   to: 'static_pages#contact', as: 'contact'
  match '/signup',    to: 'users#new',            as: 'signup',   via: 'get'
  match '/signin',    to: 'sessions#new',         as: 'signin',   via: 'get'
  match '/signout',   to: 'sessions#destroy',     as: 'signout',  via: 'delete'
  match '/edit_post', to: 'posts#edit',           as: 'editpost'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :state, :title, :tags_attributes, :tag_list, :permalink
  belongs_to :user

  has_many :tags, dependent: :destroy

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k,v| v.blank? } }
    
  has_permalink :title
  
  validates :permalink, presence: true
  validates :user_id, presence: true
  validates :body, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validates :state, presence: true
  default_scope order: 'posts.created_at DESC'

  
	DRAFT_STATE = 0
	COMPLETE_STATE = 1
	PUBLISH_STATE = 2
	TOSS_STATE = 3


  def tag_list
    self.tags.map { |t| t.name }.join(", ")
  end

  def tag_list=(new_value)
    tag_names = new_value.split(/,\s+/)
    self.tags = tag_names.map { |name| Tag.where('name = ?', name).first or Tag.create(:name => name) }
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessible :name
  	belongs_to :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :posts, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: 	{ with: VALID_EMAIL_REGEX }, 
  					uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed 
    Post.where("user_id = ?", id)
  end

  private 
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include PostsHelper


  # Force signout to prevent CSRF attacks
  def handle_inverified_request
  	signout
  	super
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
	before_filter :signed_in_user, only: [:create, :destroy, :update]
	before_filter :correct_user,   only: :destroy

	def index
		@state = params[:state] || {}
		@posts = current_user.posts.where(@state).paginate(page: params[:page])
	end 

	def show
	  @post = Post.find_by_permalink(params[:id])
	 
	  respond_to do |format|
	    format.html  # show.html.erb
	    format.json  { render :json => @post }
	  end
	end

	def create
		@post = current_user.posts.build(params[:post])
		if @post.save
			flash[:success] = "Post created!"
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

	def edit
		@post = Post.find_by_permalink(params[:id])
	end

	def update
	  @post = Post.find_by_permalink(params[:id])
 
	  respond_to do |format|
	    if @post.update_attributes(params[:post])
	      format.html  { redirect_to(@post,
	                    :notice => 'Post was successfully updated.') }
	      format.json  { head :no_content }
	    else
	      format.html  { render :action => "edit" }
	      format.json  { render :json => @post.errors,
	                    :status => :unprocessable_entity }
	    end
	  end
	end

	def destroy
		@post.update_attributes(state: 3)
		redirect_to root_url
	end

	private
		def correct_user
			@post = current_user.posts.find_by_permalink(params[:id])
			redirect_to root_url if @post.nil?
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create 
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@post = current_user.posts.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include PostsHelper
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(:state => 2).paginate(page: params[:page])
  end

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit 
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    # Before filters
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	#Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end


	def current_state=(state)
		@current_state = state
	end

	def current_state
		@current_state ||= state_from_remember_token
	end

	def current_state?(state)
    	state == current_state
  	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def current_user?(user)
    	user == current_user
  	end

  	def signed_in_user
  		unless signed_in?
  			store_location
  			redirect_to signin_url, notice: "Please sign in."
  		end
  	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
	  redirect_to(session[:return_to] || default)
	  session.delete(:return_to)
	end

	def store_location
	  session[:return_to] = request.url
	end
	
	private
		def user_from_remember_token
			remember_token = cookies[:remember_token]
			User.find_by_remember_token(remember_token) unless remember_token.nil?
		end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", 	about_path %></li>
			<li><%= link_to "Contact", 	contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>

          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Posts <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All", posts_path %></li>
                <li><%= link_to "Published", posts_path(:state => {:state => 2}) %></li>
                <li><%= link_to "Completed", posts_path(:state => {:state => 1}) %></li>
                <li><%= link_to "Drafts", posts_path(:state => {:state => 0}) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Tossed", posts_path(:state => {:state => 3}) %>
                </li>
              </ul>
            </li>

            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", posts_path(:state => {:state => 2}) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% else %>

            <li><%= link_to "Sign in", signin_path %></li>

          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">		
		<% flash.each do |key, value| %>
	        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	    <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li> 
	<span class="content"><%= post.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</span>
	<% if current_user?(post.user) %>
		<%= link_to "delete", post, method: :delete,
									data: { confirm: "You sure?" },
									title: post.title %>
	<% end %>
</li>

app/views/posts/_post.html.erb
<li> 
	<span class="title"><%= post.title %></span>
	<span class="body"><%= post.body %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(post.created_at) %> ago.
	</span>
	<% if current_user?(post.user) %>
		<%= link_to "edit", edit_post_path(post) %>
		<%= link_to "delete", post, method: :delete,
									data: { confirm: "You sure?" },
									title: post.title %>
	<% end %>
</li>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_for(@post) do |f| %>
  <%= render 'shared/post_form', f: f %>
  <%= f.submit "Update", class: "btn btn-large btn-primary" %>
<% end %>
<%= link_to 'back', root_path %> |
<%= link_to "delete", @post, method: :delete, 
										 data: { confirm: "You sure?" },
										 title: @post.title %>

app/views/posts/index.html.erb
<% provide(:title, 'Posts') %>
<h1>Posts</h1>

<%= will_paginate %>

<ul class="posts">
  <%= render @posts %>
</ul>

<%= will_paginate %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @post.body %>
  <%= @post.state %>
</p>
 
<p>
  <b>Tags:</b>
  <%= join_tags(@post) %>
</p>
 
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if !@feed_items.nil? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<div>
		<span class="title"><%= feed_item.title %></span>
		<div>
			<span class="body"><%= feed_item.body %></span>
		</div>
		  <b>Tags:</b>
		  <%= feed_item.tag_list %>
	</div>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "edit", edit_post_path(feed_item) %>
		<%= link_to "delete", feed_item, method: :delete, 
										 data: { confirm: "You sure?" },
										 title: feed_item.title %>
	<% end %>
</li>

app/views/shared/_nsigned_in_user.html.erb
<div class="center hero-unit">
<h1>Welcome to the Sample App</h1>
<h2>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</h2>
<%= link_to "Sign up now!", signup_path, 
                            class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_post_form.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<div class="titlearea" >
		<%= f.text_area :title, placeholder: "title" %>
	</div>
	<%= f.text_area :body, placeholder: "compost new post..." %>
	<h2>Tags</h2>
	<%= render :partial => 'tags/form',
			   :locals => {:form => f} %>
   </div>
	<%= f.select :state, [["publish", 2],["complete", 1],["draft", 0]] %>
</div>

app/views/shared/_signed_in_user.html.erb
<div class="row">
<aside class="span4">
  <section>
    <%= render 'shared/user_info' %>
  </section>
  <section>
    <%= render 'shared/post_form' %>
  </section>
</aside>
</div> 

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h3>
	<%= current_user.name %>
</h3>
<span>
	<%= pluralize(current_user.posts.where(:state => 2).count, "published post") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<h1>About Us</h1>
<p>
	The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	is a project to make a book and screencasts to teach web development
	with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This 
	is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title,'Contact Us') %>
<h1>Contact Us</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the 
	<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the 
	<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<section class="indent-1">
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <% @post.tags.build %>
        <%= form_for(@post) do |f| %>
          <%= render 'shared/post_form', f: f %>
          <%= f.submit "Post", class: "btn btn-large btn-primary" %>
        <% end %>
      </section>
    </aside>
    <section>
      <h3>Post Feed</h3>
      <%= render 'shared/feed' %>
    </section>
  </div>
</section>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= form.text_field :tag_list %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
  <% end %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= render 'shared/user_info', current_user: @user %>
			</h1>
		</section>
	</aside>
	<div class="span8">
    <% if @user.posts.any? %>
      <h3> Posts </h3>
	      <ol class="posts">
	        <%= render @posts %>
	      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>